<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Alenas-MacBook.local" name="core.CreditCardValidationTest" tests="80" failures="4" timestamp="2020-04-30T04:19:51 PDT" time="0.661" errors="0">
  <testcase name="luhn" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.012" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.024" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.009" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.012" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.167" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.016" classname="core.CreditCardValidationTest">
    <failure type="java.lang.AssertionError" message="
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was &lt;true&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was <true>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at core.CreditCardValidationTest.luhn(CreditCardValidationTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- luhn -->
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.016" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.012" classname="core.CreditCardValidationTest">
    <failure type="java.lang.AssertionError" message="
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was &lt;true&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was <true>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at core.CreditCardValidationTest.luhn(CreditCardValidationTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- luhn -->
  <system-out/>
  <testcase name="luhn" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.006" classname="core.CreditCardValidationTest">
    <failure type="java.lang.AssertionError" message="
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was &lt;true&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was <true>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at core.CreditCardValidationTest.luhn(CreditCardValidationTest.java:48)
at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- luhn -->
  <system-out/>
  <testcase name="exp" time="0.008" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.024" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.010" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.006" classname="core.CreditCardValidationTest">
    <failure type="java.lang.AssertionError" message="
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was &lt;true&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: Luhn of: 5584-3989-2997-3080, should be valid
     but: was <true>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at core.CreditCardValidationTest.luhn(CreditCardValidationTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- luhn -->
  <system-out/>
  <testcase name="luhn" time="0.011" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.005" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.007" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.006" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="cvv" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="luhn" time="0.010" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="type" time="0.003" classname="core.CreditCardValidationTest"/>
  <system-out/>
  <testcase name="exp" time="0.004" classname="core.CreditCardValidationTest"/>
  <system-out/>
</testsuite> <!-- core.CreditCardValidationTest -->
